spring.datasource.url=jdbc:mysql://localhost:3306/thebrandbird
spring.datasource.username=emsuser
spring.datasource.password=ems123
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true